name: check ready for release

on: pull_request_review

jobs:
  check:
    name: label when approved
    runs-on: ubuntu-latest

    steps:
      - name: Label 'ready for release' when approved pull requests
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "ready for release"
